### PR TITLE
Stop generating version.lisp via autoconf.

### PR DESCRIPTION
**Pull request by snmsts**
I know there's no benefit for people using autoconf.

to make c-mera  installable via roswell (https://github.com/roswell/roswell) via ``ros install kiselgra/c-mera``. it's better to get rid of dependency on autoconf.

### CODE REVIEW

**Comment by kiselgra** [comment]
Hi,

when you build stuff from source, will you not at some point encounter packages using autoconf?

But your patch looks very interesting, I'll have a look at it (but sadly only in two or three weeks).

Thanks!

**Comment by snmsts** [comment]
What I got from ``./configure`` was

```
(in-package :c-mera)

(defparameter *version* (list 1.0.1 1.0.1 1.0.1))
(defparameter *generator* :undefined)

(defun print-version ()
  (format t "~a.~a.~a~%" (first *version*) (second *version*) (third *version*)))
```

On osx setting. May be still something wrong.

I think what I've done except ``cm.ros`` is quite simple.and ``cm.ros`` doesn't do any harm to people who aren't using roswell.

I'm just waiting other two weeks for review. :)

**Comment by snmsts** [comment]
Should I wait more?

**Comment by snmsts** [comment]
Thank you. ;)

**Comment by lispbub** [comment]
You're Welcome :)
I've fixed an addition issue that occurred when i tried to load c-mera with roswell.
(i relocated a function-definition to another file)

It seems to work pretty well :)

**Pull request merged**
